# Generated by Django 2.2.24 on 2021-07-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customtext_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='login',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
